### PR TITLE
removed unused variable

### PR DESCRIPTION
**Pull request by stoffu**
Supposed to solve #64 & #61

### CODE REVIEW

**Comment by BigslimVdub** [comment]
Has there been a discussion (possibly from Sarang) if ring size 3 is even fungible?

Are both the bulletproofs and Ring-CT code already in Aeon or does it still need to be merged? If not then when is it scheduled to be added? Some of the community members had the impression that both would be added and activated sometime in November 2018. 

I know that the activation code was disabled on the 12.0 rebase release for Ring CT - 
```
Activation of RingCT: PR-961
Enforcement of RingCT & minimum mixin 4: PR-1869
```

**Comment by abhishek1104** [comment]
I am also for 5 min settings.(post studying Transaction size,if it remains better in terms of size than existing one atleast by 1/4th of current transaction size ignoring 0 mixing cases,with assumption of future growth in Aeon Transaction volume)

Though keeping it fixed is how better than using mixing of say 11 ?
My point is don't fix it just keep 5 at minimum....

If it would have been above 10 then fixing it at that point was OK i would assume though keeping the light weight perspective of Aeon which is must to have,I am not saying to keep min that high

**Comment by iamsmooth** [comment]
And btw, again, I wasn't actually suggesting mandatory 3 (not sure anyone did), only pointing out that is the _minimum_ number that might be even remotely considered. What I actually said:

> That said, I'm not disagreeing with 5, just keeping options open

**Comment by iamsmooth** [comment]
> after looking at the current distribution

I don't know what the current distribution has do with anything. The current AEON has no RingCT and we're discussing one with RingCT. That's completely different in terms of protocol and tradeoffs, and more than that, upon switching to RingCT, pre-RingCT outputs would never be selected.

EDIT: my mistake. I didn't see this: "Updated initial comment to include this discussion for ONLY either removal of ring sizes 1-4 and 5 being the default or removal selectable ring sizes and using a single fixed ring size. Leaving out the discussion for Ring CT / Bulletproofs enabling to another discussion"

So never mind. Carry on. Whatever changes could be made now would be revisited with RingCT/BP

**Comment by BigslimVdub** [comment]
Locked ring 3 as noted in pr #136 
Closing

**Pull request merged**
