### PR TITLE
Fix for Windows build (on AppVeyor)

### PR DESCRIPTION
**Pull request by stoffu**
Those lines commented out are the same as in the Monero codebase.

### CODE REVIEW

**Comment by ghost** [comment]
I don't think we should have an Appveyor file in the official repo. Not very decentralizedesque.

**Comment by ghost** [comment]
That said, fixing the Appveyor build is very helpful. Thanks @stoffu!

**Comment by stoffu** [comment]
@xmr-eric OK, I dropped the appveyor.yml file and changed the title accordingly.

**Comment by Arux-BTT** [comment]
i am in favour of merging an appveyor file in the official repo for several reasons:

- it doesn't pollute excessively the repo. only one identified file with an explicite name at the root.

- it allows to everybody to build windows binaries without any special software requirement.

- classical windows compilation is unmodified, you are free to use or not appveyor.

**Comment by iamsmooth** [comment]
@Arux-BTT I'm going to merge this as submitted (without appveyor) but if you want appveyor feel free to add it it in another PR. I have objection to your reasoning about including it.

**Pull request merged**
