### PR TITLE
Fixed macOS Sierra Install issue

### PR DESCRIPTION
**Pull request by ArtSabintsev**
On macOS 10.12.5, there is an installation issue when running `make`

```
[ 24%] Building C object src/CMakeFiles/crypto.dir/crypto/oaes_lib.c.o
/Users/Arthur/Downloads/aeon-0.9.12.0/src/crypto/oaes_lib.c:37:10: fatal error: 'malloc.h' file not found
#include <malloc.h>
         ^
1 error generated.
make[3]: *** [src/CMakeFiles/crypto.dir/crypto/oaes_lib.c.o] Error 1
make[2]: *** [src/CMakeFiles/crypto.dir/all] Error 2
make[1]: *** [all] Error 2
make: *** [build-release] Error 2
```

The fix is changing the `<import malloc.h>` statement to `<import malloc.h/malloc.h>` in two files:

- oaes_lib.c
- alloca.h

I'm not sure why all the extra whitespaces were added. Maybe because my editors (Xcode and Atom) is set for spaces. vs tabs?

### CODE REVIEW

**Comment by neilalexander** [comment]
I also noticed this issue on Sierra, however I believe that `malloc.h` is not even needed, as it is already defined in `stdlib.h`. Instead I did:

```
#if !defined(__MACH__)
#include <malloc.h>
#endif
```

**Comment by aeonix** [comment]
I'm not sure that malloc/malloc.h would be okay on every other platform, therefore I prefer @neilalexander 's suggested fix, being narrow to the platform with the observed problem. Please resubmit using that approach.

**Comment by stoffu** [comment]
FYI this is Monero's current code:
```c++
#if !defined(__APPLE__) && !defined(__FreeBSD__) && !defined(__OpenBSD__) \
  && !defined(__DragonFly__)
 #include <malloc.h>
#endif
```
https://github.com/monero-project/monero/blob/master/src/crypto/oaes_lib.c#L37

Also I think `alloca.h` is only relevant to MinGW build and needs no change.

**Comment by blasut** [comment]
any updates on this? Could we use Moneros solution?

**Comment by sammy007** [comment]
You must install command line tools. There is no need for monero solution.

https://github.com/aeonix/aeon/issues/85

**Comment by matiasinsaurralde** [comment]
Installing the command line tools fixes the issue, thanks! 👍

**Pull request closed without merging**
